# Generated by Django 4.1.1 on 2022-09-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
